### ISSUE TITLE
Inline function call comments get moved from parameters to beyond function call

### ISSUE THREAD

**Issue by paustint** [dangmai/prettier-plugin-apex#371] opened 2021-05-20 21:17 UTC
```json
# Prettier options (if any):
{
  "trailingComma": "none",
  "singleQuote": true,
  "printWidth": 140,
  "overrides": [
    {
      "files": "**/classes/**/*.cls",
      "options": { "tabWidth": 4 }
    },
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc", "tabWidth": 4 }
    },
    {
      "files": "*.{cmp,page,component,email}",
      "options": { "parser": "html", "tabWidth": 4 }
    },
    {
      "files": "*.hbs",
      "options": { "parser": "glimmer" }
    }
  ]
}

```

**Input:**

```apex
ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY,
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE,
    ids,
    '0120L000000Re8LQAS'  // Legacy Standard
);
```

**Actual output:**

```apex
ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY,
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE,
    ids,
    '0120L000000Re8LQAS'
); // Legacy Standard
```

**Expected output:**

```apex
ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY,
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE,
    ids,
    '0120L000000Re8LQAS' // Legacy Standard
);
```

**Additional information (please fill this out)**:

- OS: OSX
- Version: 
```json
"prettier": "^2.3.0",
"prettier-plugin-apex": "^1.9.1"
```

**Comment by paustint** [comment] 2021-05-20 21:18
It appears to only happen on final line
```java
        ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
            ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY, // test 1
            ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE, // test 2
            ids, // test 3
            '0120L000000Re8LQAS' // Legacy Standard
        );
```
```java
ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY, // test 1
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE, // test 2
    ids, // test 3
    '0120L000000Re8LQAS'
); // Legacy Standard
```

**Comment by paustint** [comment] 2021-05-20 21:35
Here is another related weird edge-case

```java
ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY,
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE,
    ids,
    [SELECT Id, Name, IsActive FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'Legacy Standard'].Id
);
```

Output - I would not expect `.Id` to be put on a new line, as it is not outside of the function call
```java
ManualRecordUpdateBatch batch = new ManualRecordUpdateBatch(
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE_QUERY,
    ManualRecordUpdateBatch.UPDATE_OPP_REC_TYPE,
    ids,
    [SELECT Id, Name, IsActive FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'Legacy Standard']
    .Id
);
```

**Comment by dangmai** [comment] 2021-05-20 22:32
Thanks for the bug report @paustint, the last issue is duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/319 which I'm procrastinating working on because it's _difficult_&trade;

I think I can handle the comment issue though, it depends on how `jorje` attaches that comment node.

**Closed** 2021-05-21 14:53 UTC

**Comment by dangmai** [comment] 2021-05-21 14:55
I fixed the comment issue in `master`, it will be in the next release. The other issue you mentioned will be tracked in #319
