### ISSUE TITLE
Cannot execute plugin from webstorm

### ISSUE THREAD

**Issue by zainabian** [dangmai/prettier-plugin-apex#349] opened 2021-04-05 15:30 UTC
Hi i am attempting to use the plugin to format my code on Webstorm 2020.1.3, IlluminatedCloud2 and Mac Pro laptop.
I have installed prettier and this plugin and used the config file set by my team. 
When i try to execute the command, i first see a prompt from the laptop asking my to trash my JDK file and then get the following error:

> Error: spawnSync /Users/myProject/IdeaProjects/testPrettierSetup/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer EPIPE
>     at Object.spawnSync (internal/child_process.js:1045:20)
>     at spawnSync (child_process.js:597:24)
>     at parseTextWithSpawn (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier-plugin-apex/src/parser.js:25:27)
>     at Object.parse (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier-plugin-apex/src/parser.js:489:21)
>     at Object.parse (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier/index.js:13575:19)
>     at coreFormat (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier/index.js:14851:25)
>     at format (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier/index.js:15073:14)
>     at formatWithCursor (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier/index.js:15090:12)
>     at /Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier/index.js:54691:12
>     at Object.format (/Users/zainabshikari/IdeaProjects/testPrettierSetup/node_modules/prettier/index.js:54711:12)
> Process finished with exit code -1

**Comment by dangmai** [comment] 2021-04-05 15:42
Hi, thank you for opening the bug report. The stack trace points to some issue with calling the JAR file - and this looks like a Mac environment? Which version of JRE/JDK are you running and which OS?

**Comment by dangmai** [comment] 2021-04-09 17:49
I think this might be a duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/350 I just released version `1.9.0` that should fix that particular issue. Could you try that version and see if it works? If it doesn't, feel free to reopen this bug report with more detail. Thanks!

**Closed by dangmai** 2021-04-09 17:49 UTC
