### ISSUE TITLE
Execute permissions on apex-ast-serializer

### ISSUE THREAD

**Issue by gbreavin** [dangmai/prettier-plugin-apex#10] opened 2019-01-03 22:27 UTC
I took the plugin for a spin: npm install and ran it on an existing set of triggers and classes. I was flooded with errors, root cause was because the files in node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/ do not have the execute permission.

Don't know enough about node and npm packages to understand how this could be resolved, so not sure if there's a fix in the way the apex plugin is registered with prettier, or if there needs to be an addition to the README with a `chmod +x` step.

**Comment by dangmai** [comment] 2019-01-03 22:35
Hi, thank you for the bug report! Can I ask how you installed the package (globally? locally?) and which OS you are using?

**Comment by gbreavin** [comment] 2019-01-03 22:54
Apologies, how could I forget those details!

I'm on a Mac running Mojave and I installed locally. NPM Version is 6.4.1 and Node Version is 8.10.0

Now that I'm thinking on it, I did have some initial issues with installation... I was in a Salesforce DX project directory without a package.json. I think the initial install actually worked, but one of the warnings was that there wasn't a package.json. I created it and ran the installation command again.

I'll try and recreate the issue but may not be until next week

**Comment by dangmai** [comment] 2019-01-03 23:01
No worries! I managed to reproduce it on my way using a Ubuntu VM. You're right that it is an executable bit that need to be set on a few files on a *nix system. I'll make sure that those are included in the next release.

**Comment by dangmai** [comment] 2019-01-03 23:19
Fixed in 09ecc676bfa0b7a8426c16a3b486e8f57d6b790a

I've also released a new version for this on NPM, and on Linux it's now working fine. Please update and let me know if you still run into it or any other issue.

**Closed by dangmai** 2019-01-03 23:19 UTC
Labels: bug

**Comment by gbreavin** [comment] 2019-01-03 23:21
Thanks! And thanks for your work on this plugin - really looking forward to using it!

**Comment by Confirm4Crit** [comment] 2019-06-10 17:13
Hey @dangmai, I'm having the same issue:
npm -v
6.9.0
node -v
v11.0.0
Mac Mojave
npm ERR! path /Users/me/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer-ng
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/me/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer-ng'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Is there a workaround for this?

**Comment by dangmai** [comment] 2019-06-10 17:17
@Confirm4Crit My bad, it's because I changed the underlying file structure but forgot to update the `package.json` file. I'll release a new version with the fix - expect it in an hour or so.

**Comment by dangmai** [comment] 2019-06-10 17:40
@Confirm4Crit I just published `1.0.0-rc.2`. Could you try again with that version to see if your issue is resolved?

**Comment by Confirm4Crit** [comment] 2019-06-10 17:49
@dangmai All good, thanks for the quick turn around!
