### ISSUE TITLE
Formatting issue with bindings in a GEOLOCATION statement in a SOQL query

### ISSUE THREAD

**Issue by dhallsim** [dangmai/prettier-plugin-apex#92] opened 2019-07-09 20:51 UTC
**Input:**
```apex
private Id queryClosest(Double latitude, Double longitude, Double distance) {
  List<Account> closest = [
    SELECT Id, BillingAddress
    FROM Account
    WHERE DISTANCE(BillingAddress, GEOLOCATION(:latitude, :longitude), 'mi') < :distance
    ORDER BY DISTANCE(BillingAddress, GEOLOCATION(:latitude, :longitude), 'mi')
    LIMIT 1
  ];
  return (!closest.isEmpty() ? closest[0].Id : null);
}
```

**Output:**
Cannot read property '$' of undefined

**Expected behavior:**
When the geolocation parts for the method get commented out, the code is formatted as expected. It only happens when I bind the latitude and longitude variables into the GEOLOCATION parts of the query. If I hard code decimal values in for the latitude and longitude, it formats as expected and does not throw an error.

**Additional information (please fill this out)**:

- OS: OSX 10.14.5
- Version: 1.0.0-rc.5

**Comment by dangmai** [comment] 2019-07-09 23:27
Thank you for the report. This is a duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/90 which I've already fixed in `master` and will be included in the next version

**Closed by dangmai** 2019-07-09 23:27 UTC
