### ISSUE TITLE
Comments after class definition are removed

### ISSUE THREAD

**Issue by paustint** [dangmai/prettier-plugin-apex#301] opened 2020-10-30 15:10 UTC
Sort of an edge-case, but it was very unexpected.

I had some block comments after the class definition (outside the closing `}`) and when formatting ran, these were stripped from my fil :sob:.

```sh
# Prettier options (if any):
{
  "trailingComma": "none",
  "apexInsertFinalNewline": false,
  "singleQuote": true,
  "printWidth": 140,
  "overrides": [
    {
      "files": "**/classes/**/*.cls",
      "options": { "tabWidth": 4 }
    },
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc", "tabWidth": 4 }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html", "tabWidth": 4 }
    }
  ]
}
```

**Input:**

```apex
public class ApexConstants {
// ...redacted in this example
}
// This is another test comment
/**
I have some notes here that are temporary as I work through something
 */

```

**Actual output:**

```apex
public class ApexConstants {
// ...redacted in this example
}
```

**Expected output:**

```apex
public class ApexConstants {
// ...redacted in this example
}
// This is another test comment
/**
I have some notes here that are temporary as I work through something
 */
```

**Additional information (please fill this out)**:

- OS: OSX
- Version: `"^1.7.0"`

**Comment by dangmai** [comment] 2020-10-30 15:12
Oh no! That definitely is not supposed to happen, I'll fix this soon

**Comment by dangmai** [comment] 2020-10-30 15:16
Interesting, I can't reproduce this in my environment. If possible could you post the entire input file? I used your input and the comments were there after the format happened.

**Comment by paustint** [comment] 2020-10-30 15:40
I can reproduce with this. Are you sure you have the same settings? (e.x. `"apexInsertFinalNewline": false,`)

![Screen Recording 2020-10-30 at 9 37 24 AM](https://user-images.githubusercontent.com/5461649/97725395-be4a7f00-1a93-11eb-9c25-0b6b30c7c84a.gif)


```
["INFO" - 9:37:26 AM] Prettier Options:
{
  "filepath": "/.../force-app/main/default/classes/ApexConstants.cls",
  "parser": "apex",
  "trailingComma": "none",
  "apexInsertFinalNewline": false,
  "singleQuote": true,
  "printWidth": 140,
  "tabWidth": 4
}
["INFO" - 9:37:27 AM] Formatting completed in 961.904933ms.
```

```apex
public class ApexConstants {

    public static List<String> additionalFieldsToPopulateOnTwin = new List<String>{
        'SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.EndDate',
        // QLG fields so that the group can be cloned on amendments
        'SBQQ__Opportunity2__r.SBQQ__AmendedContract__r.SBQQ__Quote__r.Primary_Quote_Line_Group__r.Name',
        // QLG fields so that the group can be cloned on renewals
        'SBQQ__Opportunity2__r.SBQQ__RenewedContract__r.SBQQ__Quote__r.Primary_Quote_Line_Group__r.Name'
    };
}
// TEST
/**
CAN WE SEE IF WE CAN ADD THESE TO THE MAPPING FROM CONTRACT TO QLG INSTEAD OF HARD-CODING?

::MISSING::
CDN_Commit__c
CDN_Commit_Type__c
RMP_Violation_Percentage__c


Cloned_From_Quote_Line_Group__c (DELETE ME)
Custom_Waterfall_Schema__c (SKIP ME)
Opt_In__c (SKIP ME)
Previous_List_Total__c (SKIP ME)
 */
```

**Comment by dangmai** [comment] 2020-10-30 15:46
You're right, somehow the `apexInsertFinalNewline` option makes the trailing comments disappear. I'm debugging this now. Thank you for the reproducible case!

**Comment by dangmai** [comment] 2020-11-16 18:25
Just a note that I haven't forgotten this issue - I've had to delve deep within Prettier comment handling system multiple times to understand its behavior, and it looks like Prettier requires a newline at the end of the file to flush out trailing comments. I'm still trying to think of a way to work around it, but because it's in upstream code base and not mine - it's limiting a lot of my options. The obvious way to fix it is to add a trailing empty line anyway, and remove it in some kind of postprocessing if `apexInsertFinalNewLine` is set, but it doesn't look like Prettier has the post-processing mechanism in place for plugins, so I'm still looking for another way.

**Comment by dangmai** [comment] 2020-11-18 15:20
My PR to fix this upstream has been merged, so the next version of Prettier should fix this. I'm going to keep this open until I can test it with their new release. It will require you to pin your package.json Prettier version to their upcoming version.

**Comment by dangmai** [comment] 2020-11-20 16:55
Prettier 2.2.0 is out now with the fix for this issue, please upgrade your dependency and it should fix your problem.

**Closed by dangmai** 2020-11-20 16:55 UTC

**Comment by paustint** [comment] 2020-11-21 00:41
dude. You are awesome!
