### ISSUE TITLE
No indentation when wrapping field reference after SOQL query

### ISSUE THREAD

**Issue by adammyhre** [dangmai/prettier-plugin-apex#524] opened 2022-05-09 19:36 UTC
**Input:**

```apex
Date actualDate = [SELECT myCustomDateField__c FROM MyCustomObject__c WHERE id = :record.id].myCustomDateField__c;
```

**Actual output:**

```apex
Date actualDate = [SELECT myCustomDateField__c FROM MyCustomObject__c WHERE id = :record.id]
.myCustomDateField__c;
```

**Expected output:**

```apex
Date actualDate = [SELECT myCustomDateField__c FROM MyCustomObject__c WHERE id = :record.id]
    .myCustomDateField__c
```

**Additional information (please fill this out)**:

- OS: Windows 10
- Version: 1.10.0

**Comment by dangmai** [comment] 2022-05-09 19:59
Thank you for opening the ticket. You're right that the formatting in this instance is not ideal, I'll put this in the backlog of things to fix in the next versions.

**Comment by dangmai** [comment] 2022-05-13 16:53
I just realized that this is a duplicate of #319. I will keep the other one open and close this one, so we can track progress in one place.

**Closed by dangmai** 2022-05-13 16:53 UTC
