### ISSUE TITLE
Excessively long classpath affects windows

### ISSUE THREAD

**Issue by jwoodwardffdc** [dangmai/prettier-plugin-apex#645] opened 2022-09-21 15:01 UTC
Our developers that use windows machines get errors when they try to use Prettier on apex files.
We are invoking a command like this (via runOnSave in VisualStudio)
`c:\Users\Chris\Documents\myproject\common/autoinstallers/rush-githooks/node_modules/.bin/prettier --write c:\Users\Chris\Documents\myproject\force-app\main\default\classes\TMR_TimerSessions.cls --config ../../.prettierrc --plugin prettier-plugin-apex`

The stack in the error tells us to look at `apex-ast-serializer.bat`, and by doing some debugging it seems line 70 is causing the problem. (set CLASSPATH= …) This line is huge, and when `%APP_HOME%` is resolved it hits the maximum length of a command in windows. (8192 characters)
I count 48 instances of %APP_HOME% and if they are replaced by a path of over 139 characters you will hit the limit. A typical value for one user having a problem is
`C:\Users\Chris\Documents\asp-just-fine\common\autoinstallers\rush-githooks\node_modules\.pnpm\prettier-plugin-apex@1.8.0_prettier@2.7.1\node_modules\prettier-plugin-apex\vendor\apex-ast-serializer\bin\\lib\`

One possible fix might be to replace the line with
`set CLASSPATH=%APP_HOME%\lib\` which is nice and short, not sure if there are downsides to doing this.

**Comment by dangmai** [comment] 2022-09-27 23:16
Hello, thank you for opening the issue!

You're right that this is an issue, it's caused by Gradle Application plugin, which is used to package apex-ast-serializer. This has been fixed by https://github.com/dangmai/prettier-plugin-apex/pull/651 and will be included in the next release.

Thanks again!

**Closed by dangmai** 2022-09-27 23:16 UTC
