### ISSUE TITLE
Unrecognized option: --add-opens=java.base/java.lang=ALL-UNNAMED

### ISSUE THREAD

**Issue by sjurgis** [dangmai/prettier-plugin-apex#362] opened 2021-04-29 21:20 UTC
Trying this plugin with husky. It works on another brand new repo I work on, but tried to add to older one and it fails to execute:

```
➜  sfdx git:(master) ✗ git commit -m 'wip'
husky > pre-commit (node v14.15.1)
✔ Preparing...
✔ Hiding unstaged changes to partially staged files...
⚠ Running tasks...
  ❯ Running tasks for **/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}
    ✖ prettier --write --tab-width 4 [FAILED]
  ↓ No staged files match **/{aura|lwc}/** [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ prettier --write --tab-width 4:
[error] decsond/main/core/classes/Maps.cls: Error: spawnSync /Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer EPIPE
[error]     at Object.spawnSync (internal/child_process.js:1067:20)
[error]     at spawnSync (child_process.js:602:24)
[error]     at parseTextWithSpawn (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier-plugin-apex/src/parser.js:25:27)
[error]     at Object.parse (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier-plugin-apex/src/parser.js:489:21)
[error]     at Object.parse (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier/index.js:13625:19)
[error]     at coreFormat (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier/index.js:14899:14)
[error]     at format (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier/index.js:15131:14)
[error]     at Object.formatWithCursor (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier/index.js:57542:12)
[error]     at format (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier/bin-prettier.js:15883:14)
[error]     at Object.formatFiles (/Users/heyoo/workspace/DND/sfdx3/sfdx/node_modules/prettier/bin-prettier.js:16067:16)
```

Executing the prettier directly:
```
➜  sfdx git:(master) ✗ ./node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer
Unrecognized option: --add-opens=java.base/java.lang=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

```
```
        "prettier": "^2.2.1",
        "prettier-plugin-apex": "^1.9.1",
```
```
➜  sfdx git:(master) ✗ which java
/Users/heyoo/.sdkman/candidates/java/current/bin/java
```

```
➜  sfdx git:(master) ✗ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```
MacOs latest

**Comment by dangmai** [comment] 2021-04-29 21:29
Hi, this is duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/357 We no longer support JDK8, please update to AdoptOpenJDK 11 or higher.

**Closed by dangmai** 2021-04-29 21:29 UTC

**Comment by sjurgis** [comment] 2021-04-29 21:30
Thanks, this starting to make sense - newer repo had 1.6.0 which works ok.
