### ISSUE TITLE
Adds extra new line at end of file.  Salesforce removes this

### ISSUE THREAD

**Issue by ChuckJonas** [dangmai/prettier-plugin-apex#141] opened 2019-11-14 16:48 UTC
```json
{
  "trailingComma": "none",
  "printWidth": 120,
  "tabWidth": 4,
  "overrides": [
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    }
  ]
}
```

**Input:**

```apex
public class Foo {
}
```

**Actual output:**

```apex
public class Foo {
}

```

**Expected output:**

```apex
public class Foo {
}
```

**Additional information (please fill this out)**:

Prettier is adding an extra newline at the end of the file.  While I don't mind this from a formatting POV, when you deploy your code to Salesforce, it gets removed!

This is extremely inconvenient as any time you refresh the file from salesforce it will be marked as changed!

- OS: OSX
- Version: 
"prettier": "1.19.1",
"prettier-plugin-apex": "1.0.0",

**Comment by dangmai** [comment] 2019-11-14 16:54
Thanks for the bug report, this is a duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/83
I added an option to disable the final newline. Note that other Prettier supported languages do not have that option, so if you use Prettier in those contexts you'll have to figure out a way to handle this issue.

**Closed by dangmai** 2019-11-14 16:54 UTC

**Comment by ChuckJonas** [comment] 2019-11-14 17:00
Thanks, adding `"apexInsertFinalNewline": false,` solved it. 

FYI, in my opinion the default should match Salesforce.   Otherwise your code base gets whiplashed to death with this whitespace change.  

Given that it doesn't _really_ make a different if this newline is there or not, why would you NOT make it the default?

**Comment by dangmai** [comment] 2019-11-14 17:11
This plugin is stuck between 2 ecosystems that have different opinions on final newlines (Salesforce vs Prettier) and I made the decision to follow Prettier as default, since it's the upstream project. I know Prettier core's philosophy about this and they will never change the default behavior, so my hope is that Salesforce will someday preserve the final newlines correctly.

**Comment by ChuckJonas** [comment] 2019-11-14 17:29
I understand you're reasoning on this, **BUT...**

Given that this particular extension of prettier is ONLY valid in the context of Salesforce (what do you do with apex except push it to Salesforce?), I personally would have sided with the Salesforce convention by default.  

Instead we've created a scenario where pretty much every project needs an extra configuration point.  

@capeterson what are the chances Apex would start preserving a newlines at the end of the file in the foreseeable future?

**Comment by dangmai** [comment] 2019-11-14 17:36
I do understand the inconvenience, hopefully it'll be a short term one if Salesforce decides to preserve newlines correctly.

At this point that default is not going to change since a major version is out, changing it will lead to a lot more confusion for users when they upgrade.

**Comment by ChuckJonas** [comment] 2019-11-14 17:47
ya totally understandable.  Depending on what @capeterson says, maybe it should be considered for the next major release. 

cheers
