### ISSUE TITLE
Error formatting document

### ISSUE THREAD

**Issue by Techley-git** [dangmai/prettier-plugin-apex#357] opened 2021-04-21 03:07 UTC
Apologies if this is the wrong place to file this. Looks specific to the apex formatter. Followed salesforce guide for enabling it.
Having trouble formatting the apex class ClassName (anonymized from the actual name, user from my actual /Users/name) 

"INFO" - 8:04:21 PM] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 8:04:21 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 8:04:21 PM] Prettier Options:
{
  "filepath": "c:\\Users\\user\\SFDX VSC\\EOSProd4-13-21NonManaged\\force-app\\main\\default\\classes\\ClassName.cls",
  "parser": "apex",
  "trailingComma": "none"
}
["ERROR" - 8:04:21 PM] Error formatting document.
Error: 
	at parseTextWithSpawn (c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier-plugin-apex\src\parser.js:36:11)
	at Object.parse (c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier-plugin-apex\src\parser.js:489:21)
	at Object.parse (c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier\index.js:13625:19)
	at coreFormat (c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier\index.js:14899:14)
	at format (c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier\index.js:15131:14)
	at c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier\index.js:57542:12
	at Object.format (c:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged\node_modules\prettier\index.js:57562:12)
	at t.default.<anonymous> (c:\Users\user\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:16897)
	at Generator.next (<anonymous>)
	at s (c:\Users\user\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:9119)
["INFO" - 8:04:21 PM] Formatting completed in 206.891001ms.

**Comment by dangmai** [comment] 2021-04-21 03:14
Hi, thanks for opening the bug report. Which version of prettier apex are you running?

**Comment by Techley-git** [comment] 2021-04-21 03:28
I just ran the npm install so I would assume the latest? How do I check?

**Comment by dangmai** [comment] 2021-04-21 03:30
You can run this command in your project folder:

```
npm ls prettier-plugin-apex
```

And paste the result here.

**Comment by Techley-git** [comment] 2021-04-21 03:31
Awesome! On my list for tomorrow!

**Comment by btamburrino** [comment] 2021-04-21 20:10
@dangmai I got this error as well on a new repo. My ls showed `prettier-plugin-apex@1.9.0`.

When I changed our package.json from "^1.8.0" to "1.8.0" in order to explicitly install `prettier-plugin-apex@1.8.0` the error went away.

I'm on Windows 10, FWIW.

**Comment by Techley-git** [comment] 2021-04-22 00:07
my package json has 
` "prettier-plugin-apex": "^1.6.0"`

but `npm ls prettier-plugin-apex` gives 
```
salesforce-app@1.0.0 C:\Users\user\SFDX VSC\EOSProd4-13-21NonManaged
`-- prettier-plugin-apex@1.9.0 
```

**Comment by dangmai** [comment] 2021-04-22 00:10
I see, I'm not 100% sure what the issue is yet; however Prettier Apex 1.9.0 [drops support for Java < 11](https://github.com/dangmai/prettier-plugin-apex/releases/tag/v1.9.0), which I believe is the root cause here. My suggestion is to figure out which version of Java you're running, and if it's an old one you should upgrade to AdoptOpenJDK11 or later.

**Comment by btamburrino** [comment] 2021-04-22 00:20
At least in my case I am still on Java 8 (??!) because obviously I never thought about my Java installation since I built this computer.

I'll upgrade it tomorrow. You're probably right on that being the cause.

**Comment by Techley-git** [comment] 2021-04-22 00:47
@dangmai  seems right on for java version... I have to keep 1.8 for another application that has only partial support for java 11
java -version
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)

Any way for me to set prettier apex to an earlier version?

**Comment by dangmai** [comment] 2021-04-22 14:26
Hi, you can run this command in your project dir to pin an older version of Prettier Apex that supports Java 8:

```
npm install prettier-plugin-apex@1.8.0 --save-dev --save-exact
```

You can also have multiple versions of Java installed in your machine, and choose to use one by changing the `JAVA_HOME` environment variable, but it's out of scope for this project.

Thanks again for the bug report!

**Closed by dangmai** 2021-04-22 14:26 UTC

**Comment by btamburrino** [comment] 2021-04-22 15:56
@dangmai Just confirming that upgrading to 11 fixed the issue on my end. Thanks so much for the quick response!
