### ISSUE TITLE
Boolean values in SOQL queries are formatted to lowercase

### ISSUE THREAD

**Issue by NightwingOfGotham** [dangmai/prettier-plugin-apex#224] opened 2020-06-04 15:53 UTC
I've noticed that when writing SOQL in Apex with Boolean values in the SOQL, Prettier reformats the `TRUE` and `FALSE` values to `true` and `false`.  I think that it's just treating those values like they are in Apex and not in SOQL, but I haven't actually looked into it.

Example, Prettier will turn this query:

```
List<Pokemon> goodPokemon = [
    SELECT Name
    FROM Pokemon
    WHERE IsGood = TRUE
 ];
```

Into this query:

```
List<Pokemon> goodPokemon = [
    SELECT Name
    FROM Pokemon
    WHERE IsGood = true
 ];
```

**Comment by dangmai** [comment] 2020-06-04 15:59
Hi, thanks for the report. This is a duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/209. I do take into account everyone's opinion, and it seems that a lot of people do want the uppercase keywords in SOQL, so there's a good chance that it'll change in a future version.

**Closed by dangmai** 2020-06-04 15:59 UTC
