### ISSUE TITLE
Error when parsing apex code

### ISSUE THREAD

**Issue by Kxa422** [dangmai/prettier-plugin-apex#119] opened 2019-08-30 13:17 UTC
When I try to parse any Apex code, the following error appear

Cannot read property 'split' of undefined

**Comment by dangmai** [comment] 2019-08-30 16:00
Thank you for the report. Could you post the command that you use and the configuration file (if it exists)? If this issue happens on every Apex file then it's highly likely that the issue lies in one of those places

**Comment by Kxa422** [comment] 2019-08-30 20:24
From vscode, command palette, format document

File .pretierrc
{
    "trailingComma": "none",
    "tabWidth": 4,
    "apexInsertFinalNewline": true,
    "apexStandaloneParser": "none",
    "overrides": [
        {
            "files": "**/lwc/**/*.html",
            "options": { "parser": "lwc" }
        },
        {
            "files": "*.{cmp,page,component}",
            "options": { "parser": "html" }
        }
    ]
}

Package.json
{
  "name": "ToMyGitName",
  "version": "1.0.0",
  "description": "Some description here",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ToMyGitFile.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/ToMyGitFile/issues"
  },
  "homepage": "https://github.com/ToMyGitFile#readme",
  "devDependencies": {
    "prettier": "1.18.2",
    "prettier-plugin-apex": "1.0.0-rc.6"
  }
}

**Comment by dangmai** [comment] 2019-09-02 19:00
I have tried using the same `.prettierrc` file that you posted, and everything works fine for me in Windows 10 & VSCode 1.37.1. Do you mind giving more information about what environment you're in? (Operating System/VS Code version) Also if you see a stack trace in VSCode when the issue happened, could you post this here? Thanks

**Comment by Kxa422** [comment] 2019-09-02 19:15
Windows 10, VCode 1.37.1
Output console for Prettier is empty
All working fine with lightning component

**Comment by dangmai** [comment] 2019-09-02 19:16
Hmm that's very interesting. Where do you see the message `Cannot read property 'split' of undefined`?

**Comment by Kxa422** [comment] 2019-09-02 19:19
There is a notification at the bottom right of VSCode with that message when I try to use Format code

**Comment by dangmai** [comment] 2019-09-02 19:26
Do you mind posting your VSCode workspace and/or user settings? I can't think of anything in this library that could likely throw that exception

**Comment by Kxa422** [comment] 2019-09-02 19:42
Workspace settings
// Place your settings in this file to overwrite the default settings
{
    "workbench.startupEditor": "newUntitledFile",
    "git.enableSmartCommit": true,
    "salesforcedx-vscode-core.push-or-deploy-on-save.enabled": true,
    "workbench.colorTheme": "Codey Midnight",
    "git.autofetch": true,
    "salesforcedx-vscode-core.orgBrowser.enabled": true,
    "salesforcedx-vscode-lightning.showLightningExplorer": true,
    "salesforcedx-vscode-core.retrieve-test-code-coverage": true,
    "salesforcedx-vscode-apex.enable-sobject-refresh-on-startup": true,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.tabWidth": 4,
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}

User settings
{
  "terminal.integrated.env.osx": {
    "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
  },
  "terminal.integrated.env.linux": {
    "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
  },
  "terminal.integrated.env.windows": {
    "SFDX_SET_CLIENT_IDS": "sfdx-vscode"
  },
  "eslint.nodePath": "c:\\Users\\MyUser\\.vscode\\extensions\\salesforce.salesforcedx-vscode-lwc-46.12.0\\node_modules",
  "html.suggest.angular1": false,
  "html.suggest.ionic": false
}

**Comment by dangmai** [comment] 2019-09-02 19:48
That all looks fine to me. I'll ping someone in Salesforce to see if they can help you further.

@ntotten, have you seen this issue before?

**Comment by Kxa422** [comment] 2019-09-13 08:17
Just tried to add that part in my workspace file settings.json

When I open a class file with cls as extension, command palette, format code
 
Cannot read property 'split' of undefined

![image](https://user-images.githubusercontent.com/8321111/64847630-5a52c600-d607-11e9-84f9-090a82deef14.png)

**Comment by Kxa422** [comment] 2019-09-13 13:21
Found something that could help you in the Log (Extension Host)

[2019-09-13 14:16:32.417] [exthost] [error] [esbenp.prettier-vscode] provider FAILED
[2019-09-13 14:16:32.417] [exthost] [error] TypeError: Cannot read property 'split' of undefined
	at addFilePath (c:\Users\MyUser\.vscode\extensions\esbenp.prettier-vscode-2.2.2\out\errorHandler.js:50:23)
	at Object.safeExecution (c:\Users\MyUser\.vscode\extensions\esbenp.prettier-vscode-2.2.2\out\errorHandler.js:83:21)
	at c:\Users\MyUser\.vscode\extensions\esbenp.prettier-vscode-2.2.2\out\PrettierEditProvider.js:135:31
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\MyUser\.vscode\extensions\esbenp.prettier-vscode-2.2.2\out\PrettierEditProvider.js:4:58)

**Comment by dangmai** [comment] 2019-09-13 22:42
So that error is thrown by the Prettier VSCode plugin, not by this library. Here's something you can try to see if we can get to the root cause:
In your `c:\Users\MyUser.vscode\extensions\esbenp.prettier-vscode-2.2.2\out\errorHandler.js`, add this at line 50:

```
if (!msg) {
  return "";
}
```
This should go right before the line `const lines = msg.split('\n');`

Afterwards try formatting again, hopefully this time we can get a better stack trace of what went wrong.

**Comment by Kxa422** [comment] 2019-09-15 10:38
When changing that part of code, it remove the split error but now the formatting is not working.
Nothing in logs

**Comment by Kxa422** [comment] 2019-09-19 19:44
How can I debug / breakpoint that part ? It could help ?

**Comment by dangmai** [comment] 2019-09-19 19:52
I'm not sure to be honest, I am not the maintainer for the VSCode Prettier plugin so I'm not familiar with the code base. I think you can open an issue on their repo at https://github.com/prettier/prettier-vscode I will keep this issue open here and see if I can come up with other ways to debug this.

**Comment by dangmai** [comment] 2019-09-24 15:33
Another thing I'd like to check: What is the version of Java and NodeJS that you have installed on your machine?

**Comment by Kxa422** [comment] 2019-09-26 13:09
java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

node --version
v10.16.3

**Comment by dangmai** [comment] 2019-11-16 18:38
Hi, I know it's been a long time since we chatted about this, did you find any progress on this issue yet?

Unfortunately I'll have to close this issue, since I don't think it has anything to do with this project. The Prettier VSCode team might know more on how to debug this.

Good luck!

**Closed by dangmai** 2019-11-16 18:38 UTC
